apiVersion: 1
kind: instance-spec
image: trace_dns:main
name: upstream-dns-health
paramValues:
  # Monitor coredns' namepsace
  operator.KubeManager.namespace: kube-system

  # Monitor coredns pods' label
  operator.KubeManager.selectors: k8s-app=kube-dns

  # Monitor traffic involving the upstream nameserver (FIXME: Update IP)
  operator.filter.filter: nameserver.addr==10.224.0.91

  # Specify fields of interest
  operator.cli.fields: src,name,id,qr,qtype,rcode,latency_ns
